#!/usr/bin/env python3
import sys
from anthropic import Anthropic
from postline import Message, Service

MODEL = "claude-sonnet-4-5"

class Agent (Service):

    def __init__ (self):
        super().__init__()
        self.client = Anthropic()
        self.history = []
        pass

    def append(self, msg, replay = False):
        From = msg.get("From")
        if From != self.address():
            role = "user"
        else:
            role = "assistant"

        content = msg.format(True)
        self.history.append({
            "role": role,
            "content": content,
        })

    def generate (self):
        print(self.history, file=sys.stderr)
        sys.stderr.flush()

        response = self.client.messages.create(
            model=MODEL,
            max_tokens=4096,
            messages=self.history,
        )

        text = response.content[0].text

        print("=" * 20, file=sys.stderr)
        print(text, file=sys.stderr)
        print("=" * 20, file=sys.stderr)
        sys.stderr.flush()

        msg = Message.parse(text)
        return msg

    def on_init (self, resp):
        pass

    def on_memory (self, msg):
        self.append(msg, True)

    def on_call (self, msg, resp):
        self.append(msg, False)
        reply = self.generate()
        self.append(reply, False)
        resp.append(reply)

if __name__ == "__main__":
    agent = Agent()
    agent.run()
