#!/usr/bin/env python3
import sys
from openai import OpenAI
from postline import Message

MODEL='gpt-5.5'


def update_response_fields(reply, request):
    reply.updateResponseFields(request)
    reply.set("type", "agent:message")
    reply.set("Session-ID", request.get("Session-ID"))


class History:

    def __init__ (self):
        self.history = []

    def append (self, msg):
        From = msg.get('From')
        if From == 'user':
            role = "user"
        else:
            role = "assistant"
        content = msg.format(True)
        self.history.append({'role': role, 'content': content})


    def respond (self, client):
        print(self.history, file=sys.stderr)
        sys.stderr.flush()
        response = client.responses.create(model=MODEL,
                                           input = self.history)

        print("=" * 20, file=sys.stderr)
        print(response.output_text, file=sys.stderr)
        print("=" * 20, file=sys.stderr)
        sys.stderr.flush()
        msg = Message.parse(response.output_text)
        return msg


def handle_message(msg, history, client, fd_out):
    history.append(msg)

    if client is None:
        client = OpenAI()

    reply = history.respond(client)
    history.append(reply)
    update_response_fields(reply, msg)

    reply.write(fd_out)
    return client


def main():

    fd_in = sys.stdin.fileno()
    fd_out = sys.stdout.fileno()

    Message({
        "type": "handshake:hello",
        "spawn_type": 0,
        "history_mode": 1,
    }).write(fd_out)

    msg = Message.read(fd_in)

    client = None
    history = History()
    if msg.get('type') == 'handshake:begin_memory':
        while True:
            msg = Message.read(fd_in)
            if msg.get('type') == 'handshake:end_memory':
                msg = None
                break
            # handle history
            history.append(msg)

    while True:
        try:
            if msg is None:
                msg = Message.read(fd_in)
        except EOFError:
            break

        if msg.get('type') == 'handshake:bye':
            break

        if msg.get('type') == 'handshake:multi':
            for _ in range(msg.get("count")):
                client = handle_message(Message.read(fd_in), history, client, fd_out)
        else:
            client = handle_message(msg, history, client, fd_out)

        msg = None


if __name__ == "__main__":
    main()
