#!/usr/bin/env python3
import argparse
import os
import sys
import json

from openai import OpenAI
from postline import Message, Service, updateAccounting

#OPENAI_URL = 'https://api.openai.com/v1/chat/completions'
#OPENAI_MODEL = 'gpt-5.4-mini-2026-03-17'
OPENROUTER_URL = "https://openrouter.ai/api/v1"
OPENROUTER_MODEL = "google/gemma-3-4b-it"
DEFAULT_MODEL = OPENROUTER_MODEL

PROMPT = [
"""From: user
To: ai
Subject: Hello

On this platform we communicate with emails.  Try respond in email format.
""",
"""From: ai
To: user
Subject: Re: Hello

Understood.  We will use email to communicate.
""",
"""From: user
To: ai
Subject: shell tutorial

You can run shell commands by sending a message with `To: shell`, and set `Subject: the command to run`.  Try run the fortune command for me.
""",
"""From: ai
To: shell
Subject: fortune

""",
"""From: shell
To: ai
Subject: exit status 0

--stdout
Life is to you a dashing and bold adventure.
""",
"""From: ai
To: user
Subject: Re: shell tutorial

I successfully ran the fortune command. Here's what it returned:

"Life is to you a dashing and bold adventure."

""",
"""From: user
To: ai
Subject: shell tutorial 2

If the email body is not empty, it will be fed to the command as stdin.  Try save the fortune you got into ./fortune.txt by running `Subject: cat > fortune.txt` and supply the text as email body.
""",
"""From: ai
To: shell
Subject: cat > fortune.txt

Life is to you a dashing and bold adventure.
""",
"""From: shell
To: ai
Subject: exit status 0

""",
"""From: ai
To: user
Subject: Re: shell tutorial 2

The file is created.
"""
]

PROVIDER = "openai-compatible"


class Agent (Service):

    def __init__ (self, url, model, headers):
        super().__init__()
        api_key = None
        if url.startswith("https://openrouter.ai/"):
            api_key = os.environ.get("OPENROUTER_API_KEY")
            self.provider = 'openrouter'
        else:
            api_key = os.environ.get("OPENAI_API_KEY")
            self.provider = 'openai'
        self.client = OpenAI(
            api_key=api_key,
            base_url=url,
            default_headers=headers,
        )
        self.models = []
        self.model_ids = set()
        for m in self.client.models.list():
            self.model_ids.add(m.id)
            self.models.append(dict(m))
        self.model = model
        self.history = []
        for txt in PROMPT:
            self.append(Message.parse(txt))
        pass

    def append(self, msg):
        From = msg.get("From")
        if From != self.address():
            role = "user"
        else:
            role = "assistant"

        content = msg.format(True)
        self.history.append({
            "role": role,
            "content": content,
        })

    def generate (self):
        print(self.history, file=sys.stderr)
        sys.stderr.flush()

        response = self.client.chat.completions.create(
            model=self.model,
            messages=self.history,
        )

        text = response.choices[0].message.content

        print("=" * 20, file=sys.stderr)
        print(text, file=sys.stderr)
        print("=" * 20, file=sys.stderr)
        sys.stderr.flush()

        msg = Message.parse(text)
        updateAccounting(response, msg, self.provider)
        return msg

    def on_init (self, resp):
        pass

    def on_memory (self, msg):
        self.append(msg)

    def on_call (self, msg, resp):
        if msg.get('Subject') == '/list_models':
            resp.append(Message({}, json.dumps(self.models, indent=2)))
            return

        self.append(msg)
        model = msg.get("Model-Requested")
        if model in self.model_ids:
            self.model = model
        reply = self.generate()
        self.append(reply)
        resp.append(reply)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--provider",
        default="openrouter",
        help=f"provider"
    )
    parser.add_argument(
        "--model",
        default=None,
        help=f"Model name. Defaults to {DEFAULT_MODEL}",
    )
    args = parser.parse_args()
    if args.provider == 'openai':
        assert False, "Not supported"
    elif args.provider == 'openrouter':
        args.url = OPENROUTER_URL
        if args.model is None:
            args.model = OPENROUTER_MODEL
    else:
        assert args.provider is None

    return args


if __name__ == "__main__":
    args = parse_args()
    headers = {}
    agent = Agent(args.url, args.model, headers)
    agent.run()

